env:
  TERM: xterm-256color

font:
  size: 11.5
  # The normal (roman) font face to use.
  normal:
    family: MesloLGS Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: MesloLGS Nerd Font
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: MesloLGS Nerd Font
    # Style can be specified to pick a specific face.
    # style: Italic

window:
  dynamic_title: true
live_config_reload: true


# Colors (Snazzy)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#eff0eb'

  # Normal colors
  normal:
    black:   '#282a36'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

  # Bright colors
  bright:
    black:   '#686868'
    red:     '#ff5c57'
    green:   '#5af78e'
    yellow:  '#f3f99d'
    blue:    '#57c7ff'
    magenta: '#ff6ac1'
    cyan:    '#9aedfe'
    white:   '#f1f1f0'

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  # - { key: Add, mods: Control, action: IncreaseFontSize }
  # - { key: Subtract, mods: Control, action: DecreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: N, mods: Control, action: SpawnNewInstance }
