env:
  TERM: xterm-256color

  #shell:
  #    program: /usr/local/bin/tmux
  #    args:
  #      - -u # use UTF8
scrolling:
  history: 20000
  multiplier: 8

font:
  size: 14
  # The normal (roman) font face to use.
  normal:
    family: Hack Nerd Font Mono
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    # Style can be specified to pick a specific face.
    family: Hack Nerd Font Mono
    # style: Bold

  # The italic font face
  italic:
    family: Hack Nerd Font Mono
    # Style can be specified to pick a specific face.
    # style: Italic

window:
  dynamic_title: true
live_config_reload: false

# https://terminal.sexy
colors:
  # Default colors
  primary:
    background: '0x111111'
    foreground: '0xcccccc'

  # Normal colors
  normal:
    black:   '0x282a2e'
    red:     '0xff4e4e'
    green:   '0x96fc4a'
    yellow:  '0xf69b5c'
    blue:    '0x6fbbf9'
    magenta: '0xa261b9'
    cyan:    '0x8bfeef'
    white:   '0xefefef'

  # Bright colors
  bright:
    black:   '0x373b41'
    red:     '0xf08383'
    green:   '0xc5df9a'
    yellow:  '0xf0d090'
    blue:    '0xc5e1f8'
    magenta: '0xbf8cce'
    cyan:    '0xb1efe6'
    white:   '0xffffff'

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: N, mods: Control, action: SpawnNewInstance }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
