# Don't print a new line at the start of the prompt
add_newline = false

# Disables the line_break module, making the prompt a single line.
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[❯](bold green)"

[directory]
read_only = " "
truncate_to_repo = false
truncation_length = 5

[gcloud]
disabled = true

[package]
disabled = true

