# Don't print a new line at the start of the prompt
add_newline = false

# Disables the line_break module, making the prompt a single line.
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[❯](bold green)"

[directory]
read_only = " "
truncate_to_repo = false
truncation_length = 5

[aws]
disabled = true
#symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled = true
#symbol = " "

[dart]
disabled = true
#symbol = " "

[docker_context]
symbol = " "

[elixir]
disabled = true
#symbol = " "

[elm]
disabled = true
#symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
disabled = true
#symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
disabled = true
#symbol = "ﯣ "

