#include whitelist-player-common.inc
noblacklist ${HOME}/Desktop
whitelist ${HOME}/Desktop
noblacklist ${HOME}/Downloads
whitelist ${HOME}/Downloads
noblacklist ${HOME}/Music
whitelist ${HOME}/Music
noblacklist ${HOME}/Pictures
whitelist ${HOME}/Pictures
noblacklist ${HOME}/Videos
whitelist ${HOME}/Videos
noblacklist ${HOME}/Documents
whitelist ${HOME}/Documents

whitelist ${HOME}/tmp
#whitelist ${HOME}/ws

